apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hello

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: app-config
    files:
      - manifest.json

generatorOptions:
  disableNameSuffixHash: true
