apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: bg-demo-app
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        app: bg-demo-app
    spec:
      containers:
      - name: nginx
        image: <+artifact.image>
        ports:
        - containerPort: 80
